// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
